CREATE SCHEMA IF NOT EXISTS `dogs`;
USE `dogs` ;

CREATE TABLE IF NOT EXISTS `dogs`.`dogs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `birthday` DATE NULL DEFAULT NULL,
  `size` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;